SELECT CONCAT('홍','길동') FROM DUAL;
SELECT 3 || '4' FROM DUAL (문자열 합치는 연산);
SELECT LTRIM('     HELLO     ')FROM DUAL;
SELECT LOWER('nEwIEC') FROM DUAL;
SELECT UPPER('nEwIEC') FROM DUAL;
SELECT * FROM MEMEBER WHERE UPPRER(로우행) = '대문자'; 하면 다 검색 가능
SELECT REPLACE('WE ARE THE','WE','YOU') FROM DUAL; 통째로 바뀐다
SELECT TRANSLATE('WE ARE THE','WE','YOU') FROM DUAL; W는Y로 E는O로 바뀐다
SELECT TRIM(BUYER_NAME) 이름,
       REPLACE(BUYER_ADD1,' ','') 주소 --빈칸을 모두 없앤다
FROM   BUYER;




