SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO,PL/SQL');
END;
/
DECLARE
    V_EMPNO NUMBER(4):= 7788;
    V_ENAME VARCHAR2(10);
BEGIN
    V_ENAME:= 'SCOTT';
    DBMS_OUTPUT.PUT_LINE('V_ENAME: '|| V_ENAME);
END;
/
DECLARE
    V_EMPNO NUMBER(4):= 7788;
    V_ENAME VARCHAR2(10):='SCOTT';
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_EMPNO: '|| V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('V_ENAME: '|| V_ENAME);
END;
/
DECLARE 
    V_EMPNO NUMBER(2) NOT NULL DEFAULT 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_EMPNO: '|| V_EMPNO);
END;
/
DECLARE
    V_NUMBER NUMBER:= 13;
BEGIN
    IF MOD(V_NUMBER, 2) = 1 THEN
        DBMS_OUTPUT.PUT_LINE('홀수입니다');
    END IF;
END;
/
DECLARE
    V_SCORE NUMBER := 87;
BEGIN
    CASE TRUNC(V_SCORE/10)
        WHEN 10 THEN DBMS_OUTPUT.PUT_LINE('A');
        WHEN 9 THEN DBMS_OUTPUT.PUT_LINE('B');
        WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('C');
        WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('D');
        WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('E');
        WHEN 5 THEN DBMS_OUTPUT.PUT_LINE('F');
        ELSE DBMS_OUTPUT.PUT_LINE('G');
    END CASE;
END;
/
DECLARE
    V_NUM NUMBER :=0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('현재 V_NUM '||V_NUM);
        V_NUM:=V_NUM+1;
        EXIT WHEN V_NUM >4;
    END LOOP;
END;
/
BEGIN
    FOR I IN 0..4 LOOP
    DBMS_OUTPUT.PUT_LINE(I);
    END LOOP;
END;
/
BEGIN
    FOR I IN 0..4 LOOP
    CONTINUE WHEN MOD(I,2)=1;
    DBMS_OUTPUT.PUT_LINE(I);
    END LOOP;
END;
/
DECLARE
    TYPE REC_DEPT IS RECORD(
        DEPTNO NUMBER(2) NOT NULL :=99,
        DNAME  HR.DEPARTMENTS.DEPARTMENT_NAME%TYPE,
        LOC    HR.LOCATIONS.CITY%TYPE
    );
    DEPT_REC REC_DEPT;
BEGIN
    DEPT_REC.DEPTNO := 99;
    DEPT_REC.DNAME := 'DATABASE';
    DEPT_REC.LOC := 'SEOUL';
    DBMS_OUTPUT.PUT_LINE(DEPT_REC.DEPTNO);
    DBMS_OUTPUT.PUT_LINE(DEPT_REC.DNAME);
    DBMS_OUTPUT.PUT_LINE(DEPT_REC.LOC);
END;
/
CREATE TABLE DEPT_RECORD AS SELECT * FROM HR.DEPARTMENTS;
/
