CREATE TABLE MEMBER(
    ID VARCHAR2(10),
    NAME VARCHAR2(15),
    PW VARCHAR2(12),
    AGE NUMBER(3),
    ADDRESS VARCHAR2(100),
    MAIL VARCHAR2(30),
    PHONE VARCHAR(13),
    MILEAGE VARCHAR2(5),
    BALANCE NUMBER(6),
CONSTRAINT pk_mem_id PRIMARY KEY(ID));

CREATE TABLE ROUTE(
    BUS_NO VARCHAR2(10),
    ARRIVAL_SPOT VARCHAR2(30),
    NORMAL_FEE NUMBER(5),
    DISTANCE NUMBER(3),
    REQUIRED_TIME VARCHAR2(5),
    GRADE VARCHAR2(12),
CONSTRAINT pk_route_bus_no PRIMARY KEY(BUS_NO));

CREATE TABLE OPERATION(
    TIME_CODE VARCHAR2(6),
    BUS_NO VARCHAR2(10),
    START_TIME VARCHAR2(6),
CONSTRAINT pk_time_code PRIMARY KEY(TIME_CODE),
CONSTRAINT fk_bus_no FOREIGN KEY(BUS_NO) REFERENCES ROUTE(BUS_NO));

CREATE TABLE COMPANY(
    COM_CODE NUMBER(2),
    NAME VARCHAR2(30),
    TIME_CODE VARCHAR2(6),
    BUS_NO VARCHAR2(10),
CONSTRAINT pk_com_code PRIMARY KEY(COM_CODE),
CONSTRAINT fk_com_time_code FOREIGN KEY(TIME_CODE) REFERENCES OPERATION(TIME_CODE),
CONSTRAINT fk_com_bus_no FOREIGN KEY(BUS_NO) REFERENCES ROUTE(BUS_NO));

CREATE TABLE RESERVATION(
    RESERVE_NO NUMBER(12),
    START_TIME VARCHAR2(20),
    ADULT_TK NUMBER(6),
    CHILD_TK NUMBER(6),
    TOTAL_FEE NUMBER(6),
    SEAT_NO NUMBER(2),
    RESERVE_DATE DATE,
    USE_MILEAGE NUMBER(5),
    SAVING_MILEAGE NUMBER(5),
    ID VARCHAR2(10),
    BUS_NO VARCHAR2(10),
CONSTRAINT pk_res_reserve_no PRIMARY KEY(RESERVE_NO),
CONSTRAINT fk_res_id FOREIGN KEY(ID) REFERENCES MEMBER(ID),
CONSTRAINT fk_res_bus_no FOREIGN KEY(BUS_NO) REFERENCES ROUTE(BUS_NO));

CREATE TABLE REFUND(
    REFUND_CODE VARCHAR2(10),
    RESERVE_NO NUMBER(12),
    RDATE DATE,
CONSTRAINT pk_ref_refund_no PRIMARY KEY(REFUND_CODE),
CONSTRAINT fk_ref_reserve_no FOREIGN KEY(RESERVE_NO) REFERENCES RESERVATION(RESERVE_NO));

CREATE TABLE BUS_INFO(
    SEAT_NO NUMBER(2),
    ALL_SEAT_NO NUMBER(2),
    GRADE VARCHAR2(9),
    RESERVE_NO NUMBER(12),
CONSTRAINT pk_bus_seat_no PRIMARY KEY(SEAT_NO),
CONSTRAINT fk_bus_reserve_no FOREIGN KEY(RESERVE_NO) REFERENCES RESERVATION(RESERVE_NO));
