CREATE TABLE NOTICE
(
    ID          NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(100),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(1000)
);

CREATE TABLE COMMENTS
(
    ID          NUMBER,
    CONTENT     NVARCHAR2(2000),
    REGDATE     TIMESTAMP,
    WRITER_ID   NVARCHAR2(50),
    NOTICE_ID   NUMBER
);

RENAME COMMENTS TO "COMMENT";

ALTER TABLE "COMMENT" RENAME TO COMMENT2;
ALTER TABLE COMMENT2 RENAME TO "COMMENT";

CREATE TABLE ROLE
(
    ID      VARCHAR2(50),
    DISCRIPTION NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID      NVARCHAR2(50),
    ROLE_ID VARCHAR2(50)
);
COMMIT;




