2021/08/18-01
문자열 추출함 SUBSTR(문자열, 시작위치, 길이)
           SUBSTRB(문자열, 시작위치) 시작위치부터 다 자른다
SELECT SUBSTRB(NAME,2) FROM DUAL;
SELECT NAME, SUBSTR(BIRTHDAY, 6, 2) MONTH FROM MEMBERS;
SELECT SUBSTR(PHONE, 011%) FROM MEMBERS
SELECT * FROM MEMBERS WHERE SUBSTR(PHONE,1,3) = '011';
--조건절에 필요한 건지 무엇을 뽑아내야 되는지 쿼리를 이해해야된다. 행을 필터링인지 컬럼(열)을 추출하는 건지
SELECT * FROM MEMBERS WHERE PHONE LIKE '011%'; --웨어절에는 연산자를 쓰는게 효율적이다
SELECT * FROM MEMBERS WHERE BIRTHDAY LIKE '%07%', '%08%', '%09%';
SELECT * FROM MEMBERS WHERE SUBSTR(BIRTHDAY, 6,2) = '7' OR SUBSTR(BIRTHDAY, 6,2) = '8' OR SUBSTR(BIRTHDAY, 6,2) = '9';
SELECT * FROM MEMBERS WHERE SUBSTR(BIRTHDAY, 6,2) IN ('7', '8', '9');
SELECT * FROM MEMBERS WHERE SUBSTR(BIRTHDAY, 6,2) NOT IN ('7', '8', '9');
SELECT * FROM MEMEBER WHERE PHONE IS NULL AND SUBSTR(BIRTHDAY, 6,2) IN ('07', '08', '09');
UPDATE MEMBERS SET BIRTHDAY='1999-09-03' WHERE MID='NEWLEC';
COMMIT;

