--CREATE TABLE MEMBER
--(

 --  ID          VARCHAR2(50),
 --   PWD         VARCHAR2(50),
 --  NAME        NVARCHAR2(50),
 --  GENDER      NCHAR(2), --MAN OR WOMAN
 --  AGE         NUMBER,
 --  BIRTHDAY    CHAR(10), -- 2000-01-02
 --  PHONE       CHAR(13), --010-1234-2345
 --  REGDATE     DATE
    
--); 

--DROP TABLE MEMBER;

--INSERT INTO MEMBER(GENDER) VALUES('³²¼º');

--SELECT LENGTHB(GENDER) FROM MEMBER;

--COMMIT;

--ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
--ALTER TABLE MEMBER DROP COLUMN AGE;
--ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);
--COMMIT
